name: "camculator"

# data settings
data:
  data_dir: "./model/data/raw"
  valid_split_ratio: 0.2
  data_loader:
    args:
      batch_size: 10000
      shuffle: true
      num_workers: 2

# model settings
arch: 
  type: "CamculatorModel"
  args: []

optimizer:
  type: "Adam"
  args:
    lr: 0.008

loss: "nll_loss"

metrics:
  - "accuracy"

trainer:
  epochs: 60

  save_dir: "model/saved/"
  save_period: 1

  monitor_metric: "val_loss"

  early_stop: 5


